branch-defaults:
  main:
    environment: node-express-env
    group_suffix: null
deploy:
  artifact: ./build.zip
global:
  application_name: tracktak
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
