name: publish dcf react
on:
  pull_request:
    types: [closed]
    paths:
      - "packages/intrinsic-valuations/**"
jobs:
  publish-intrinsic-valuations:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/intrinsic-valuations
    env:
      NODE_AUTH_TOKEN: ${{ secrets.DCF_REACT_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12.20.1"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@tracktak"
      - run: npm install --only=prod
      - run: npm publish
